/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import br.PII_1_2024.modelo.Aluno;
import br.PII_1_2024.bd.AlunoDAO;
import br.PII_1_2024.bd.TurmaDAO;
import br.PII_1_2024.jogo.TelaFundoJogo;
import br.PII_1_2024.modelo.Turma;
import java.awt.BorderLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author anton
 */
public class GerenciarAluno extends javax.swing.JFrame {
    private Turma turmas;
    /**
     * Creates new form GerenciarAluno
     */
    public GerenciarAluno() {
        initComponents();        
        buscarAlunos();
        buscarTurmas();
        setResizable(false);
        setLocationRelativeTo(null);
        TelaFundoJogo t = new
            TelaFundoJogo(getClass().getResource("/images/TelaInicio.png"));
        this.setContentPane(t);
        this.setLayout(new BorderLayout());
        t.add(fundo);
        this.pack();
    }
    private void buscarAlunos (){
    try{
        var dao = new AlunoDAO();
        Aluno [] alunos = dao.obterAluno();
        alunosComboBox.setModel(new DefaultComboBoxModel<>(alunos));
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, "alunos indisponíveis, tente"
                + "novamente mais tarde.");
        e.printStackTrace();
    }
 }
    
    private void buscarTurmas (){
    try{
        var dao = new TurmaDAO();
        Turma [] t = dao.obterTurma();
        turmasComboBox.setModel(new DefaultComboBoxModel<>(t));
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, "turmas indisponíveis, tente"
                + "novamente mais tarde.");
        e.printStackTrace();
    }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        alunosComboBox = new javax.swing.JComboBox<>();
        nomeAlunoTextField = new javax.swing.JTextField();
        turmaTextField = new javax.swing.JTextField();
        novoAlunoButton = new javax.swing.JButton();
        atualizarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        idAlunoTextField = new javax.swing.JTextField();
        limparAlunoButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        turmasComboBox = new javax.swing.JComboBox<>();
        codigoTurmaTextField = new javax.swing.JTextField();
        nomeTurmaTextField = new javax.swing.JTextField();
        limparTurmaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundo.setOpaque(false);

        jPanel2.setOpaque(false);

        alunosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunosComboBoxActionPerformed(evt);
            }
        });

        nomeAlunoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("aluno"));

        turmaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("codigo da turma"));
        turmaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaTextFieldActionPerformed(evt);
            }
        });

        novoAlunoButton.setText("Novo ");
        novoAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAlunoButtonActionPerformed(evt);
            }
        });

        atualizarButton.setText("Atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        idAlunoTextField.setEditable(false);
        idAlunoTextField.setToolTipText("");
        idAlunoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("codigo do aluno"));

        limparAlunoButton.setText("Limpar");
        limparAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparAlunoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idAlunoTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(novoAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(turmaTextField)
                    .addComponent(nomeAlunoTextField)
                    .addComponent(alunosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limparAlunoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(alunosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idAlunoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(nomeAlunoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(turmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(limparAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setOpaque(false);

        turmasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmasComboBoxActionPerformed(evt);
            }
        });

        codigoTurmaTextField.setEditable(false);
        codigoTurmaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("codigo da turma"));

        nomeTurmaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("turma"));

        limparTurmaButton.setText("Limpar");
        limparTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTurmaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(limparTurmaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(nomeTurmaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(codigoTurmaTextField)
                    .addComponent(turmasComboBox, 0, 256, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turmasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(codigoTurmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(nomeTurmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(limparTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAlunoButtonActionPerformed
        String nomeAluno = nomeAlunoTextField.getText();
        String turma = turmaTextField.getText();
        if (nomeAluno == null || nomeAluno.length() == 0
                && turma == null || turma.length() == 0){
            JOptionPane.showMessageDialog (null, "Preencha o nome "
                    + "do aluno e sua turma");
        }
        else{
            try{
                int escolha = JOptionPane.showConfirmDialog(null, "Confirmar "
                        + "cadastro do novo aluno?");
                if (escolha == JOptionPane.YES_OPTION){
                    String nome = nomeAlunoTextField.getText();
                    int codigoTurma = Integer.parseInt(turmaTextField.getText());
                    Aluno aluno = new Aluno (nome, codigoTurma);
                    AlunoDAO dao = new AlunoDAO();
                    dao.inserirAluno(aluno);
                    JOptionPane.showMessageDialog(null, "Aluno cadastrado com "
                            + "sucesso");
                    nomeAlunoTextField.setText("");
                    turmaTextField.setText("");
                    buscarAlunos();
                }
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_novoAlunoButtonActionPerformed

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        String nomeAluno = nomeAlunoTextField.getText();
        String turma = turmaTextField.getText();
        String codigoAluno = idAlunoTextField.getText();
        if (nomeAluno == null || nomeAluno.length() == 0 
                && turma == null || turma.length() == 0 
                && codigoAluno == null || codigoAluno.length() == 0){
            
            JOptionPane.showMessageDialog(null, "ERRO. SELECIONE UM ALUNO");
        }
        else{    
            int escolha = JOptionPane.showConfirmDialog(null, "Atualizar aluno?");
            if (escolha == JOptionPane.YES_OPTION){
                try{
                    int idAluno = Integer.parseInt(idAlunoTextField.getText());
                    int codigoTurma = Integer.parseInt(turmaTextField.getText());
                    String nome = nomeAlunoTextField.getText();
                    Aluno aluno = new Aluno (idAluno, nome, codigoTurma);
                    AlunoDAO dao = new AlunoDAO();
                    dao.atualizarAluno(aluno);
                    JOptionPane.showMessageDialog(null, "aluno atualizado"
                            + " com sucesso");
                    buscarAlunos();
                    nomeAlunoTextField.setText("");
                    turmaTextField.setText("");
                    idAlunoTextField.setText("");
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente "
                            + "mais tarde.");
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_atualizarButtonActionPerformed

    private void alunosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunosComboBoxActionPerformed
        Aluno aluno = (Aluno) alunosComboBox.getSelectedItem();
        idAlunoTextField.setText(Integer.toString(aluno.getCodigoAluno()));
        nomeAlunoTextField.setText(aluno.getNome());
        turmaTextField.setText(Integer.toString(aluno.getCodigoTurma()));
    }//GEN-LAST:event_alunosComboBoxActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        String nomeAluno = nomeAlunoTextField.getText();
        String turma = turmaTextField.getText();
        String codigoAluno = idAlunoTextField.getText();
        if (nomeAluno == null || nomeAluno.length() == 0 
                && turma == null || turma.length() == 0 
                && codigoAluno == null || codigoAluno.length() == 0){
            
            JOptionPane.showMessageDialog(null, "ERRO."
                    + " SELECIONE UM ALUNO");
        }
        else{
            int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remove-lo?");
            if (escolha == JOptionPane.YES_OPTION){
                try{
                    int idAluno = Integer.parseInt (idAlunoTextField.getText());
                    Aluno aluno = new Aluno (idAluno);
                    AlunoDAO dao = new AlunoDAO();
                    dao.removerAluno(aluno);
                    JOptionPane.showMessageDialog(null, "aluno removido "
                            + "com sucesso!");
                    buscarAlunos();
                    nomeAlunoTextField.setText("");
                    turmaTextField.setText("");
                    idAlunoTextField.setText("");
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica."
                            + " Tente novamente mais tarde.");
                e.printStackTrace();
                }
        }
        }
    }//GEN-LAST:event_removerButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        new HUBProfessor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void turmasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmasComboBoxActionPerformed
        turmas = (Turma) turmasComboBox.getSelectedItem();
        nomeTurmaTextField.setText(turmas.getNome());
        codigoTurmaTextField.setText(Integer.toString(turmas.getCodigoTurma()));
    }//GEN-LAST:event_turmasComboBoxActionPerformed

    private void limparAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparAlunoButtonActionPerformed
        nomeAlunoTextField.setText("");
        turmaTextField.setText("");
        idAlunoTextField.setText("");
    }//GEN-LAST:event_limparAlunoButtonActionPerformed

    private void turmaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turmaTextFieldActionPerformed

    private void limparTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTurmaButtonActionPerformed
        nomeTurmaTextField.setText("");
        codigoTurmaTextField.setText("");
    }//GEN-LAST:event_limparTurmaButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Aluno> alunosComboBox;
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField codigoTurmaTextField;
    private javax.swing.JPanel fundo;
    private javax.swing.JTextField idAlunoTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton limparAlunoButton;
    private javax.swing.JButton limparTurmaButton;
    private javax.swing.JTextField nomeAlunoTextField;
    private javax.swing.JTextField nomeTurmaTextField;
    private javax.swing.JButton novoAlunoButton;
    private javax.swing.JButton removerButton;
    private javax.swing.JTextField turmaTextField;
    private javax.swing.JComboBox<Turma> turmasComboBox;
    // End of variables declaration//GEN-END:variables
}
