/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.PII_1_2024.jogo;

/**
 *
 * @author anton
 */
public class FaseCasa extends javax.swing.JFrame {

    /**
     * Creates new form FaseCasa
     */
    public FaseCasa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaFundoCasa = new javax.swing.JPanel();
        iniciarQuarto = new javax.swing.JLabel();
        iniciarSala = new javax.swing.JLabel();
        iniciarBanheiro = new javax.swing.JLabel();
        iniciarCozinha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iniciarQuarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarQuartoMouseClicked(evt);
            }
        });

        iniciarSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarSalaMouseClicked(evt);
            }
        });

        iniciarBanheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarBanheiroMouseClicked(evt);
            }
        });

        iniciarCozinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarCozinhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout telaFundoCasaLayout = new javax.swing.GroupLayout(telaFundoCasa);
        telaFundoCasa.setLayout(telaFundoCasaLayout);
        telaFundoCasaLayout.setHorizontalGroup(
            telaFundoCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoCasaLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(telaFundoCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iniciarBanheiro, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(iniciarQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(171, 171, 171)
                .addGroup(telaFundoCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iniciarSala, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(iniciarCozinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        telaFundoCasaLayout.setVerticalGroup(
            telaFundoCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaFundoCasaLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(telaFundoCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(telaFundoCasaLayout.createSequentialGroup()
                        .addComponent(iniciarCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iniciarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaFundoCasaLayout.createSequentialGroup()
                        .addComponent(iniciarBanheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(iniciarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(telaFundoCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaFundoCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarBanheiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarBanheiroMouseClicked
        dispose();
        var jogoBanheiro = new JogoDaMemoria("banheiro");
        jogoBanheiro.inicializarJogoMemoria(8, "banheiro");
        jogoBanheiro.setVisible(true);
    }//GEN-LAST:event_iniciarBanheiroMouseClicked

    private void iniciarCozinhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarCozinhaMouseClicked
        dispose();
        var jogoCozinha = new JogoDaMemoria("cozinha");
        jogoCozinha.inicializarJogoMemoria(8, "cozinha");
        jogoCozinha.setVisible(true);
    }//GEN-LAST:event_iniciarCozinhaMouseClicked

    private void iniciarQuartoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarQuartoMouseClicked
        dispose();
        var jogoQuarto = new JogoDaMemoria("quarto");
        jogoQuarto.inicializarJogoMemoria(8, "quarto");
        jogoQuarto.setVisible(true);
    }//GEN-LAST:event_iniciarQuartoMouseClicked

    private void iniciarSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarSalaMouseClicked
        dispose();
        var jogoSala = new JogoDaMemoria("sala");
        jogoSala.inicializarJogoMemoria(8, "sala");
        jogoSala.setVisible(true);
    }//GEN-LAST:event_iniciarSalaMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iniciarBanheiro;
    private javax.swing.JLabel iniciarCozinha;
    private javax.swing.JLabel iniciarQuarto;
    private javax.swing.JLabel iniciarSala;
    private javax.swing.JPanel telaFundoCasa;
    // End of variables declaration//GEN-END:variables
}
