/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.PII_1_2024.jogo;

/**
 *
 * @author anton
 */
import br.PII_1_2024.db.TurmaDAO;
import br.PII_1_2024.modelo.Turma;
import java.awt.BorderLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class GerenciarTurma extends javax.swing.JFrame {
    private Turma turma;
    /**
     * Creates new form GerenciarTurma
     */
    public GerenciarTurma() {
        initComponents();
        buscarTurmas();
        setResizable(false);
        setLocationRelativeTo(null);
        TelaFundoJogo t = new
            TelaFundoJogo(getClass().getResource("/images/TelaInicio.png"));
        this.setContentPane(t);
        this.setLayout(new BorderLayout());
        t.add(fundo);
        this.pack();
    }
    
    private void buscarTurmas (){
    try{
        var dao = new TurmaDAO();
        Turma [] turmas = dao.obterTurma();
        turmasComboBox.setModel(new DefaultComboBoxModel<>(turmas));
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, "turmas indisponíveis, tente"
                + "novamente mais tarde.");
        e.printStackTrace();
    }
 }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        turmasComboBox = new javax.swing.JComboBox<>();
        codigoTurmaTextField = new javax.swing.JTextField();
        nomeTurmaTextField = new javax.swing.JTextField();
        novaTurmaButton = new javax.swing.JButton();
        cancelarTurmaButton = new javax.swing.JButton();
        limparTextoTextField = new javax.swing.JButton();
        removerTurmaButton = new javax.swing.JButton();
        atualizarTurmaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundo.setOpaque(false);

        jPanel2.setOpaque(false);

        turmasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmasComboBoxActionPerformed(evt);
            }
        });

        codigoTurmaTextField.setEditable(false);
        codigoTurmaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("codigo da turma"));

        nomeTurmaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("turma"));

        novaTurmaButton.setText("Nova turma");
        novaTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaTurmaButtonActionPerformed(evt);
            }
        });

        cancelarTurmaButton.setText("Cancelar");
        cancelarTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarTurmaButtonActionPerformed(evt);
            }
        });

        limparTextoTextField.setText("Limpar");
        limparTextoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTextoTextFieldActionPerformed(evt);
            }
        });

        removerTurmaButton.setText("Remover");
        removerTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerTurmaButtonActionPerformed(evt);
            }
        });

        atualizarTurmaButton.setText("Atualizar");
        atualizarTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarTurmaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(removerTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(turmasComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codigoTurmaTextField)
                            .addComponent(nomeTurmaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(novaTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(atualizarTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(limparTextoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancelarTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(turmasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codigoTurmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(nomeTurmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novaTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(limparTextoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novaTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaTurmaButtonActionPerformed
        String nomeTurma = nomeTurmaTextField.getText();
        if (nomeTurma == null || nomeTurma.length() == 0 ){
            JOptionPane.showMessageDialog (null, "Preencha o nome da turma");
        }
        else{
            try{
                int escolha = JOptionPane.showConfirmDialog(null, "Confirmar cadastro "
                        + "de nova turma?");
                if (escolha == JOptionPane.YES_OPTION){
                    Turma turma = new Turma (nomeTurma);
                    TurmaDAO dao = new TurmaDAO();
                    dao.inserirTurma(turma);
                    JOptionPane.showMessageDialog(null, "Turma cadastrada com "
                            + "sucesso");
                    nomeTurmaTextField.setText("");
                    codigoTurmaTextField.setText("");
                    buscarTurmas();
                }
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_novaTurmaButtonActionPerformed

    private void atualizarTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarTurmaButtonActionPerformed
        String nomeTurma = nomeTurmaTextField.getText();
        String codigoTurma = codigoTurmaTextField.getText();
        if (nomeTurma == null || nomeTurma.length() == 0
                && codigoTurma == null || codigoTurma.length() == 0){
            
            JOptionPane.showMessageDialog(null, "ERRO. SELECIONE UMA TURMA");
        }
        else{    
            int escolha = JOptionPane.showConfirmDialog(null, "Atualizar turma?");
            if (escolha == JOptionPane.YES_OPTION){
                try{
                    int codigo = Integer.parseInt(codigoTurmaTextField.getText());
                    String nome = nomeTurmaTextField.getText();
                    Turma turma = new Turma (codigo, nome);
                    TurmaDAO dao = new TurmaDAO();
                    dao.atualizarTurma(turma);
                    JOptionPane.showMessageDialog(null, "turma atualizada"
                            + " com sucesso");
                    buscarTurmas();
                    nomeTurmaTextField.setText("");
                    codigoTurmaTextField.setText("");
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente "
                            + "mais tarde.");
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_atualizarTurmaButtonActionPerformed

    private void turmasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmasComboBoxActionPerformed
        turma = (Turma) turmasComboBox.getSelectedItem();
        nomeTurmaTextField.setText(turma.getNome());
        codigoTurmaTextField.setText(Integer.toString(turma.getCodigoTurma()));
 
    }//GEN-LAST:event_turmasComboBoxActionPerformed

    private void removerTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerTurmaButtonActionPerformed
        String nomeTurma = nomeTurmaTextField.getText();
        String codigoTurma = codigoTurmaTextField.getText();
        if (nomeTurma == null || nomeTurma.length() == 0 
                && codigoTurma == null || codigoTurma.length() == 0 ){
            
            JOptionPane.showMessageDialog(null, "ERRO. SELECIONE UMA TURMA");
        }
        else{
            int escolha = JOptionPane.showConfirmDialog(null, "Remover turma?");
            if (escolha == JOptionPane.YES_OPTION){
                try{
                    int codigo = Integer.parseInt(codigoTurmaTextField.getText());
                    Turma turma = new Turma (codigo);
                    TurmaDAO dao = new TurmaDAO();
                    dao.removerTurma(turma);
                    JOptionPane.showMessageDialog(null, "turma removida "
                            + "com sucesso!");
                    buscarTurmas();
                    nomeTurmaTextField.setText("");
                    codigoTurmaTextField.setText("");
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica."
                            + " Tente novamente mais tarde.");
                e.printStackTrace();
                }
        }
        }
    }//GEN-LAST:event_removerTurmaButtonActionPerformed

    private void cancelarTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarTurmaButtonActionPerformed
        new HUBProfessor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarTurmaButtonActionPerformed

    private void limparTextoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTextoTextFieldActionPerformed
        nomeTurmaTextField.setText("");
        codigoTurmaTextField.setText("");
    }//GEN-LAST:event_limparTextoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarTurmaButton;
    private javax.swing.JButton cancelarTurmaButton;
    private javax.swing.JTextField codigoTurmaTextField;
    private javax.swing.JPanel fundo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limparTextoTextField;
    private javax.swing.JTextField nomeTurmaTextField;
    private javax.swing.JButton novaTurmaButton;
    private javax.swing.JButton removerTurmaButton;
    private javax.swing.JComboBox<Turma> turmasComboBox;
    // End of variables declaration//GEN-END:variables
}
