/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.PII_1_2024.jogo;

import br.PII_1_2024.modelo.Aluno;
import br.PII_1_2024.db.AlunoDAO;
import br.PII_1_2024.db.TurmaDAO;
import br.PII_1_2024.modelo.Turma;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author anton
 */
public class GerenciarAluno extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarAluno
     */
    public GerenciarAluno() {
        initComponents();
        buscarAlunos();
        buscarTurmas();
    }
    private void buscarAlunos (){
    try{
        var dao = new AlunoDAO();
        Aluno [] alunos = dao.obterAluno();
        alunosComboBox.setModel(new DefaultComboBoxModel<>(alunos));
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, "turmas indisponíveis, tente"
                + "novamente mais tarde.");
        e.printStackTrace();
    }
 }
    
    private void buscarTurmas (){
    try{
        var dao = new TurmaDAO();
        Turma [] turmas = dao.obterTurma();
        turmasComboBox.setModel(new DefaultComboBoxModel<>(turmas));
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, "turmas indisponíveis, tente"
                + "novamente mais tarde.");
        e.printStackTrace();
    }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        alunosComboBox = new javax.swing.JComboBox<>();
        nomeAlunoTextField = new javax.swing.JTextField();
        turmaTextField = new javax.swing.JTextField();
        novoAlunoButton = new javax.swing.JButton();
        atualizarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        idAlunoTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        turmasComboBox = new javax.swing.JComboBox<>();
        codigoTurmaTextField = new javax.swing.JTextField();
        nomeTurmaTextField = new javax.swing.JTextField();
        limparTextoTextField = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alunosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunosComboBoxActionPerformed(evt);
            }
        });

        novoAlunoButton.setText("Novo aluno");
        novoAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAlunoButtonActionPerformed(evt);
            }
        });

        atualizarButton.setText("Atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        idAlunoTextField.setEditable(false);
        idAlunoTextField.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idAlunoTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(novoAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(turmaTextField)
                    .addComponent(nomeAlunoTextField)
                    .addComponent(alunosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alunosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(idAlunoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomeAlunoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(turmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        turmasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmasComboBoxActionPerformed(evt);
            }
        });

        codigoTurmaTextField.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeTurmaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(codigoTurmaTextField)
                        .addComponent(turmasComboBox, 0, 256, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turmasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(codigoTurmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomeTurmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        limparTextoTextField.setText("Limpar");
        limparTextoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTextoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(limparTextoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(limparTextoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAlunoButtonActionPerformed
        String nomeAluno = nomeAlunoTextField.getText();
        String turma = turmaTextField.getText();
        if (nomeAluno == null || nomeAluno.length() == 0
                && turma == null || turma.length() == 0){
            JOptionPane.showMessageDialog (null, "Preencha o nome "
                    + "do aluno e sua turma");
        }
        else{
            try{
                int escolha = JOptionPane.showConfirmDialog(null, "Confirmar "
                        + "cadastro do novo aluno?");
                if (escolha == JOptionPane.YES_OPTION){
                    String nome = nomeAlunoTextField.getText();
                    int codigoTurma = Integer.parseInt(turmaTextField.getText());
                    Aluno aluno = new Aluno (nome, codigoTurma);
                    AlunoDAO dao = new AlunoDAO();
                    dao.inserirAluno(aluno);
                    JOptionPane.showMessageDialog(null, "Aluno cadastrado com "
                            + "sucesso");
                    nomeAlunoTextField.setText("");
                    turmaTextField.setText("");
                    buscarAlunos();
                }
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_novoAlunoButtonActionPerformed

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        String nomeAluno = nomeAlunoTextField.getText();
        String turma = turmaTextField.getText();
        String codigoAluno = idAlunoTextField.getText();
        if (nomeAluno == null || nomeAluno.length() == 0 
                && turma == null || turma.length() == 0 
                && codigoAluno == null || codigoAluno.length() == 0){
            
            JOptionPane.showMessageDialog(null, "ERRO. SELECIONE UM ALUNO");
        }
        else{    
            int escolha = JOptionPane.showConfirmDialog(null, "Atualizar aluno?");
            if (escolha == JOptionPane.YES_OPTION){
                try{
                    int idAluno = Integer.parseInt(idAlunoTextField.getText());
                    int codigoTurma = Integer.parseInt(turmaTextField.getText());
                    String nome = nomeAlunoTextField.getText();
                    Aluno aluno = new Aluno (idAluno, nome, codigoTurma);
                    AlunoDAO dao = new AlunoDAO();
                    dao.atualizarAluno(aluno);
                    JOptionPane.showMessageDialog(null, "aluno atualizado"
                            + " com sucesso");
                    buscarAlunos();
                    nomeAlunoTextField.setText("");
                    turmaTextField.setText("");
                    idAlunoTextField.setText("");
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente "
                            + "mais tarde.");
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_atualizarButtonActionPerformed

    private void alunosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunosComboBoxActionPerformed
        Aluno aluno = (Aluno) alunosComboBox.getSelectedItem();
        idAlunoTextField.setText(Integer.toString(aluno.getCodigo()));
        nomeAlunoTextField.setText(aluno.getNome());
        turmaTextField.setText(Integer.toString(aluno.getCodigoTurma()));
    }//GEN-LAST:event_alunosComboBoxActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        String nomeAluno = nomeAlunoTextField.getText();
        String turma = turmaTextField.getText();
        String codigoAluno = idAlunoTextField.getText();
        if (nomeAluno == null || nomeAluno.length() == 0 
                && turma == null || turma.length() == 0 
                && codigoAluno == null || codigoAluno.length() == 0){
            
            JOptionPane.showMessageDialog(null, "ERRO."
                    + " SELECIONE UM ALUNO");
        }
        else{
            int escolha = JOptionPane.showConfirmDialog(null, "Remover aluno?");
            if (escolha == JOptionPane.YES_OPTION){
                try{
                    int idAluno = Integer.parseInt (idAlunoTextField.getText());
                    Aluno aluno = new Aluno (idAluno);
                    AlunoDAO dao = new AlunoDAO();
                    dao.removerAluno(aluno);
                    JOptionPane.showMessageDialog(null, "aluno removido "
                            + "com sucesso!");
                    buscarAlunos();
                    nomeAlunoTextField.setText("");
                    turmaTextField.setText("");
                    idAlunoTextField.setText("");
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica."
                            + " Tente novamente mais tarde.");
                e.printStackTrace();
                }
        }
        }
    }//GEN-LAST:event_removerButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        new HUBProfessor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void turmasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmasComboBoxActionPerformed
        Turma turma = (Turma) turmasComboBox.getSelectedItem();
        nomeTurmaTextField.setText(turma.getNome());
        codigoTurmaTextField.setText(Integer.toString(turma.getCodigoTurma()));
    }//GEN-LAST:event_turmasComboBoxActionPerformed

    private void limparTextoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTextoTextFieldActionPerformed
        nomeAlunoTextField.setText("");
        turmaTextField.setText("");
        idAlunoTextField.setText("");
        nomeTurmaTextField.setText("");
        codigoTurmaTextField.setText("");
    }//GEN-LAST:event_limparTextoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Aluno> alunosComboBox;
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField codigoTurmaTextField;
    private javax.swing.JTextField idAlunoTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton limparTextoTextField;
    private javax.swing.JTextField nomeAlunoTextField;
    private javax.swing.JTextField nomeTurmaTextField;
    private javax.swing.JButton novoAlunoButton;
    private javax.swing.JButton removerButton;
    private javax.swing.JTextField turmaTextField;
    private javax.swing.JComboBox<Turma> turmasComboBox;
    // End of variables declaration//GEN-END:variables
}
