/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.PII_1_2024.jogo;

/**
 *
 * @author anton
 */
import br.PII_1_2024.db.TurmaDAO;
import br.PII_1_2024.modelo.Turma;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class GerenciarTurma extends javax.swing.JFrame {
    
    /**
     * Creates new form GerenciarTurma
     */
    public GerenciarTurma() {
        initComponents();
        buscarTurmas();
    }
    
    private void buscarTurmas (){
    try{
        var dao = new TurmaDAO();
        Turma [] turmas = dao.obterTurma();
        turmasComboBox.setModel(new DefaultComboBoxModel<>(turmas));
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, "turmas indisponíveis, tente"
                + "novamente mais tarde.");
        e.printStackTrace();
    }
 }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeTurmaTextField = new javax.swing.JTextField();
        novaTurmaButton = new javax.swing.JButton();
        removerTurmaButton = new javax.swing.JButton();
        cancelarTurmaButton = new javax.swing.JButton();
        turmasComboBox = new javax.swing.JComboBox<>();
        atualizarTurmaButton = new javax.swing.JButton();
        codigoTurmaTextField = new javax.swing.JTextField();
        limparTextoTextField = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        novaTurmaButton.setText("Nova turma");
        novaTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaTurmaButtonActionPerformed(evt);
            }
        });

        removerTurmaButton.setText("Remover");
        removerTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerTurmaButtonActionPerformed(evt);
            }
        });

        cancelarTurmaButton.setText("Cancelar");
        cancelarTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarTurmaButtonActionPerformed(evt);
            }
        });

        turmasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmasComboBoxActionPerformed(evt);
            }
        });

        atualizarTurmaButton.setText("Atualizar");
        atualizarTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarTurmaButtonActionPerformed(evt);
            }
        });

        codigoTurmaTextField.setEditable(false);

        limparTextoTextField.setText("Limpar");
        limparTextoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTextoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(582, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(limparTextoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cancelarTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(novaTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(atualizarTurmaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(removerTurmaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(turmasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomeTurmaTextField)
                        .addComponent(codigoTurmaTextField)))
                .addGap(387, 387, 387))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(turmasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codigoTurmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomeTurmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novaTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(limparTextoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novaTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaTurmaButtonActionPerformed
        String nomeTurma = nomeTurmaTextField.getText();
        if (nomeTurma == null || nomeTurma.length() == 0 ){
            JOptionPane.showMessageDialog (null, "Preencha o nome da turma");
        }
        else{
            try{
                int escolha = JOptionPane.showConfirmDialog(null, "Confirmar cadastro "
                        + "de nova turma?");
                if (escolha == JOptionPane.YES_OPTION){
                    Turma turma = new Turma (nomeTurma);
                    TurmaDAO dao = new TurmaDAO();
                    dao.inserirTurma(turma);
                    JOptionPane.showMessageDialog(null, "Turma cadastrada com "
                            + "sucesso");
                    nomeTurmaTextField.setText("");
                    codigoTurmaTextField.setText("");
                    buscarTurmas();
                }
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_novaTurmaButtonActionPerformed

    private void atualizarTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarTurmaButtonActionPerformed
        String nomeTurma = nomeTurmaTextField.getText();
        String codigoTurma = codigoTurmaTextField.getText();
        if (nomeTurma == null || nomeTurma.length() == 0
                && codigoTurma == null || codigoTurma.length() == 0){
            
            JOptionPane.showMessageDialog(null, "ERRO. SELECIONE UMA TURMA");
        }
        else{    
            int escolha = JOptionPane.showConfirmDialog(null, "Atualizar turma?");
            if (escolha == JOptionPane.YES_OPTION){
                try{
                    int codigo = Integer.parseInt(codigoTurmaTextField.getText());
                    String nome = nomeTurmaTextField.getText();
                    Turma turma = new Turma (codigo, nome);
                    TurmaDAO dao = new TurmaDAO();
                    dao.atualizarTurma(turma);
                    JOptionPane.showMessageDialog(null, "turma atualizada"
                            + " com sucesso");
                    buscarTurmas();
                    nomeTurmaTextField.setText("");
                    codigoTurmaTextField.setText("");
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente "
                            + "mais tarde.");
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_atualizarTurmaButtonActionPerformed

    private void turmasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmasComboBoxActionPerformed
        Turma turma = (Turma) turmasComboBox.getSelectedItem();
        nomeTurmaTextField.setText(turma.getNome());
        codigoTurmaTextField.setText(Integer.toString(turma.getCodigoTurma()));
    }//GEN-LAST:event_turmasComboBoxActionPerformed

    private void removerTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerTurmaButtonActionPerformed
        String nomeTurma = nomeTurmaTextField.getText();
        String codigoTurma = codigoTurmaTextField.getText();
        if (nomeTurma == null || nomeTurma.length() == 0 
                && codigoTurma == null || codigoTurma.length() == 0 ){
            
            JOptionPane.showMessageDialog(null, "ERRO. SELECIONE UMA TURMA");
        }
        else{
            int escolha = JOptionPane.showConfirmDialog(null, "Remover turma?");
            if (escolha == JOptionPane.YES_OPTION){
                try{
                    int codigo = Integer.parseInt(codigoTurmaTextField.getText());
                    Turma turma = new Turma (codigo);
                    TurmaDAO dao = new TurmaDAO();
                    dao.removerTurma(turma);
                    JOptionPane.showMessageDialog(null, "turma removida "
                            + "com sucesso!");
                    buscarTurmas();
                    nomeTurmaTextField.setText("");
                    codigoTurmaTextField.setText("");
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica."
                            + " Tente novamente mais tarde.");
                e.printStackTrace();
                }
        }
        }
    }//GEN-LAST:event_removerTurmaButtonActionPerformed

    private void cancelarTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarTurmaButtonActionPerformed
        new HUBProfessor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarTurmaButtonActionPerformed

    private void limparTextoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTextoTextFieldActionPerformed
        nomeTurmaTextField.setText("");
        codigoTurmaTextField.setText("");
    }//GEN-LAST:event_limparTextoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarTurmaButton;
    private javax.swing.JButton cancelarTurmaButton;
    private javax.swing.JTextField codigoTurmaTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limparTextoTextField;
    private javax.swing.JTextField nomeTurmaTextField;
    private javax.swing.JButton novaTurmaButton;
    private javax.swing.JButton removerTurmaButton;
    private javax.swing.JComboBox<Turma> turmasComboBox;
    // End of variables declaration//GEN-END:variables
}
