 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.PII_1_2024.jogo;

import br.PII_1_2024.db.AlunoDAO;
import br.PII_1_2024.modelo.Aluno;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author anton
 */
public class LoginTelaAluno extends javax.swing.JFrame {
    private String nomeAluno;
    public static int codigoAluno;
    
    /**
     * Creates new form LoginTelaAluno
     */
    public LoginTelaAluno() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        TelaFundoJogo t = new
            TelaFundoJogo(getClass().getResource("/images/telaLoginAluno.png"));
        this.setContentPane(t);
        this.setLayout(new BorderLayout());
        t.add(imagemFundoLogin);
        this.pack();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagemFundoLogin = new javax.swing.JPanel();
        entrarButton = new javax.swing.JButton();
        nomeTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagemFundoLogin.setOpaque(false);

        entrarButton.setText("Entrar");
        entrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagemFundoLoginLayout = new javax.swing.GroupLayout(imagemFundoLogin);
        imagemFundoLogin.setLayout(imagemFundoLoginLayout);
        imagemFundoLoginLayout.setHorizontalGroup(
            imagemFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemFundoLoginLayout.createSequentialGroup()
                .addGap(476, 476, 476)
                .addComponent(entrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagemFundoLoginLayout.createSequentialGroup()
                .addContainerGap(383, Short.MAX_VALUE)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );
        imagemFundoLoginLayout.setVerticalGroup(
            imagemFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagemFundoLoginLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(entrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagemFundoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagemFundoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed
        try{
            
            var login = nomeTextField.getText();
            var aluno = new Aluno(login);
            aluno.setNome(login);
            var dao = new AlunoDAO();
            if (dao.existe(aluno)){
                JOptionPane.showMessageDialog (null, "Bem vindo, " 
                        + aluno.getNome() + "!");
                codigoAluno = dao.obterCodigo(aluno);
                new HUBJogador().setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuário inválido");
                nomeTextField.setText("");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog (null, "Problemas técnicos. Tente "
                    + "novamente mais tarde");
            e.printStackTrace();
            }
    }//GEN-LAST:event_entrarButtonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrarButton;
    private javax.swing.JPanel imagemFundoLogin;
    private javax.swing.JTextField nomeTextField;
    // End of variables declaration//GEN-END:variables
}
