/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.PII_1_2024.tela;

import br.PII_1_2024.tela.GerenciarTurma;
import br.PII_1_2024.tela.GerenciarProfessor;
import br.PII_1_2024.tela.GerenciarAluno;
import br.PII_1_2024.tela.ConsultarTela;
import br.PII_1_2024.jogo.AudioCurto;
import br.PII_1_2024.jogo.TelaFundoJogo;
import java.awt.BorderLayout;

/**
 *
 * @author anton
 */
public class HUBProfessor extends javax.swing.JFrame {
    private AudioCurto clipPlayer;
    /**
     * Creates new form HUBProfessor
     */
    public HUBProfessor() {
        clipPlayer = new AudioCurto("src/main/resources/audio/botaoSound.mp3");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);        
        TelaFundoJogo t = new
            TelaFundoJogo(getClass().getResource("/images/telaInicial.png"));
        this.setContentPane(t);
        this.setLayout(new BorderLayout());
        t.add(fundo);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        consultarButton = new javax.swing.JLabel();
        gerenciarTurmaButton = new javax.swing.JLabel();
        gerenciarProfessorButton = new javax.swing.JLabel();
        gerenciarAlunosButton = new javax.swing.JLabel();
        sairButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundo.setOpaque(false);

        consultarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botaoConsultar.png"))); // NOI18N
        consultarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarButtonMouseClicked(evt);
            }
        });

        gerenciarTurmaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botaoGerenciarTurma.png"))); // NOI18N
        gerenciarTurmaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerenciarTurmaButtonMouseClicked(evt);
            }
        });

        gerenciarProfessorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botaoGerenciarProfessor.png"))); // NOI18N
        gerenciarProfessorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerenciarProfessorButtonMouseClicked(evt);
            }
        });

        gerenciarAlunosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botaoGerenciarAluno.png"))); // NOI18N
        gerenciarAlunosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerenciarAlunosButtonMouseClicked(evt);
            }
        });

        sairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botaoSair.png"))); // NOI18N
        sairButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerenciarTurmaButton)
                            .addComponent(consultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerenciarAlunosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(gerenciarProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(sairButton)))
                .addGap(0, 444, Short.MAX_VALUE))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(gerenciarTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(consultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(gerenciarAlunosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerenciarProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarButtonMouseClicked
        clipPlayer.playSound();
        new ConsultarTela().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultarButtonMouseClicked

    private void gerenciarTurmaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerenciarTurmaButtonMouseClicked
        clipPlayer.playSound();
        new GerenciarTurma().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerenciarTurmaButtonMouseClicked

    private void gerenciarProfessorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerenciarProfessorButtonMouseClicked
        clipPlayer.playSound();
        new GerenciarProfessor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerenciarProfessorButtonMouseClicked

    private void gerenciarAlunosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerenciarAlunosButtonMouseClicked
        clipPlayer.playSound();
        new GerenciarAluno().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerenciarAlunosButtonMouseClicked

    private void sairButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonMouseClicked
        clipPlayer.playSound();
        new LoginTelaProfessor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairButtonMouseClicked

    /**
     * @param args the command line arguments
     */
       
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consultarButton;
    private javax.swing.JPanel fundo;
    private javax.swing.JLabel gerenciarAlunosButton;
    private javax.swing.JLabel gerenciarProfessorButton;
    private javax.swing.JLabel gerenciarTurmaButton;
    private javax.swing.JLabel sairButton;
    // End of variables declaration//GEN-END:variables
}
