/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.PII_1_2024.tela;

/**
 *
 * @author anton
 */
import br.PII_1_2024.tela.HUBProfessor;
import br.PII_1_2024.bd.ProfessorDAO;
import br.PII_1_2024.jogo.AudioCurto;
import br.PII_1_2024.jogo.TelaFundoJogo;
import br.PII_1_2024.modelo.Professor;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
public class LoginTelaProfessor extends javax.swing.JFrame {
    private String nomeProfessor;
    public static int codigoProfessor;
    private AudioCurto clipPlayer;
    /**
     * Creates new form LoginTela
     */
    public LoginTelaProfessor() {
        clipPlayer = new AudioCurto("src/main/resources/audio/botaoSound.mp3");
        initComponents();
        setLocationRelativeTo(null);       
        TelaFundoJogo login = new
            TelaFundoJogo(getClass().getResource("/images/telaLoginProfessor.png"));
        this.setContentPane(login);
        this.setLayout(new BorderLayout());
        // Certifique-se de que todos os componentes são adicionados ao painel da imagem
        login.add(imagemFundoLogin);
        // Certifique-se de que a janela está corretamente dimensionada
        this.pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagemFundoLogin = new javax.swing.JPanel();
        passwordTextField = new javax.swing.JPasswordField();
        loginTextField = new javax.swing.JTextField();
        voltarButton = new javax.swing.JLabel();
        entrarButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagemFundoLogin.setOpaque(false);

        voltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botaoVoltar.png"))); // NOI18N
        voltarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarButtonMouseClicked(evt);
            }
        });

        entrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botaoEntrar.png"))); // NOI18N
        entrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout imagemFundoLoginLayout = new javax.swing.GroupLayout(imagemFundoLogin);
        imagemFundoLogin.setLayout(imagemFundoLoginLayout);
        imagemFundoLoginLayout.setHorizontalGroup(
            imagemFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagemFundoLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(entrarButton)
                .addGap(482, 482, 482))
            .addGroup(imagemFundoLoginLayout.createSequentialGroup()
                .addGroup(imagemFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagemFundoLoginLayout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addGroup(imagemFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(imagemFundoLoginLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        imagemFundoLoginLayout.setVerticalGroup(
            imagemFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemFundoLoginLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(entrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagemFundoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagemFundoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButtonMouseClicked
        clipPlayer.playSound();
        try{
            
            var login = loginTextField.getText();
            var senha = new String(passwordTextField.getPassword());
            var professor = new Professor(login, senha);
            professor.setNome(login);
            professor.setSenha(senha);
            var dao = new ProfessorDAO();
            if (dao.existe(professor)){
                JOptionPane.showMessageDialog (null, "Bem vindo, " +
                professor.getNome() + "!");
                codigoProfessor = dao.obterCodigo(professor);
                new HUBProfessor().setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuário inválido");
                loginTextField.setText("");
                passwordTextField.setText("");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog (null, "Problemas técnicos. Tente "
                    + "novamente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_entrarButtonMouseClicked

    private void voltarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarButtonMouseClicked
        clipPlayer.playSound();
        new TelaDeInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel entrarButton;
    private javax.swing.JPanel imagemFundoLogin;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel voltarButton;
    // End of variables declaration//GEN-END:variables
}
