/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.PII_1_2024.tela;

/**
 *
 * @author anton
 */
import br.PII_1_2024.jogo.AudioCurto;
import br.PII_1_2024.jogo.TelaFundoJogo;
import java.awt.BorderLayout;
public class TelaMapa extends javax.swing.JFrame {
    private AudioCurto clipPlayer;
    /**
     * Creates new form TelaJogo
     */
    public TelaMapa() {
        initComponents();
        clipPlayer = new AudioCurto("src/main/resources/audio/botaoSound.mp3");
        setResizable(false);
        setLocationRelativeTo(null);
        TelaFundoJogo t = new
            TelaFundoJogo(getClass().getResource("/images/ImagemDeFases.jpg"));
        this.setContentPane(t);
        this.setLayout(new BorderLayout());
        t.add(telaDeFundoFases);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaDeFundoFases = new javax.swing.JPanel();
        iniciarHospital = new javax.swing.JLabel();
        iniciarCasaBanheiro = new javax.swing.JLabel();
        iniciarParquinho = new javax.swing.JLabel();
        iniciarEscola = new javax.swing.JLabel();
        iniciarRestaurante = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        telaDeFundoFases.setOpaque(false);

        iniciarHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarHospitalMouseClicked(evt);
            }
        });

        iniciarCasaBanheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarCasaBanheiroMouseClicked(evt);
            }
        });

        iniciarParquinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarParquinhoMouseClicked(evt);
            }
        });

        iniciarEscola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarEscolaMouseClicked(evt);
            }
        });

        iniciarRestaurante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarRestauranteMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botaoVoltar.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout telaDeFundoFasesLayout = new javax.swing.GroupLayout(telaDeFundoFases);
        telaDeFundoFases.setLayout(telaDeFundoFasesLayout);
        telaDeFundoFasesLayout.setHorizontalGroup(
            telaDeFundoFasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeFundoFasesLayout.createSequentialGroup()
                .addGroup(telaDeFundoFasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaDeFundoFasesLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(iniciarParquinho, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE))
                    .addGroup(telaDeFundoFasesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(telaDeFundoFasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iniciarCasaBanheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeFundoFasesLayout.createSequentialGroup()
                                .addComponent(iniciarEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGap(160, 160, 160)))
                .addGroup(telaDeFundoFasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeFundoFasesLayout.createSequentialGroup()
                        .addComponent(iniciarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeFundoFasesLayout.createSequentialGroup()
                        .addComponent(iniciarHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
        );
        telaDeFundoFasesLayout.setVerticalGroup(
            telaDeFundoFasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeFundoFasesLayout.createSequentialGroup()
                .addGroup(telaDeFundoFasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeFundoFasesLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(iniciarHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(telaDeFundoFasesLayout.createSequentialGroup()
                        .addGroup(telaDeFundoFasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaDeFundoFasesLayout.createSequentialGroup()
                                .addContainerGap(82, Short.MAX_VALUE)
                                .addComponent(iniciarCasaBanheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(telaDeFundoFasesLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(iniciarEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(telaDeFundoFasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniciarParquinho, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaDeFundoFases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDeFundoFases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarHospitalMouseClicked
        clipPlayer.playSound();
        dispose();
        var faseHospital = new FaseHospital();
        faseHospital.setVisible(true);
        
    }//GEN-LAST:event_iniciarHospitalMouseClicked

    private void iniciarCasaBanheiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarCasaBanheiroMouseClicked
        clipPlayer.playSound();
        dispose();
        var faseCasa = new FaseCasa();
        faseCasa.setVisible(true);
        
    }//GEN-LAST:event_iniciarCasaBanheiroMouseClicked

    private void iniciarParquinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarParquinhoMouseClicked
        clipPlayer.playSound();
        dispose();
        var faseParquinho = new FaseParquinho();
        faseParquinho.setVisible(true);
        
    }//GEN-LAST:event_iniciarParquinhoMouseClicked

    private void iniciarEscolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarEscolaMouseClicked
        clipPlayer.playSound();
        dispose();
        var faseEscola = new FaseEscola();
        faseEscola.setVisible(true);
    }//GEN-LAST:event_iniciarEscolaMouseClicked

    private void iniciarRestauranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarRestauranteMouseClicked
        clipPlayer.playSound();
        dispose();
        var faseRestaurante = new FaseRestaurante();
        faseRestaurante.setVisible(true);
    }//GEN-LAST:event_iniciarRestauranteMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        clipPlayer.playSound();
        new HUBAluno().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iniciarCasaBanheiro;
    private javax.swing.JLabel iniciarEscola;
    private javax.swing.JLabel iniciarHospital;
    private javax.swing.JLabel iniciarParquinho;
    private javax.swing.JLabel iniciarRestaurante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel telaDeFundoFases;
    // End of variables declaration//GEN-END:variables
}
